### ISSUE TITLE
transfer repo to posthtml

### ISSUE THREAD

**Issue by michael-ciniawsky** [posthtml/posthtml-load-plugins#23]
@GitScrum do you agree to transfer the repo over to the posthtml org? I requested some community effort to move as much as possible to the posthtml org and working together on core functionality for the ecosystem, maybe the cli module would also be a candidate for the org? ;)

**Comment by GitScrum** [comment]
Yes of course, I don't mind. I think this is good news. Congratulations!

**Comment by michael-ciniawsky** [comment]
yes i recommend it's a prerequisite before transfering this repo over to posthtml

**Comment by GitScrum** [comment]
Thanks!
